version: '3.2'

services:
  api:
    image: node:alpine
    volumes:
      - .:/api
    working_dir: /api
    environment:
      APP_ENV: local
      TYPEORM_CONNECTION: mysql
      TYPEORM_HOST: mysql
      TYPEORM_USERNAME: root
      TYPEORM_PASSWORD: root
      TYPEORM_DATABASE: api-db
      TYPEORM_PORT: 3306

      TYPEORM_ENTITIES: dist/infrastructure/persistence/typeorm/entities/**/*.js
      TYPEORM_MIGRATIONS_TABLE_NAME: migrations
      TYPEORM_MIGRATIONS: dist/infrastructure/persistence/typeorm/migrations/**/*.js
    depends_on:
      - mysql
    ports:
      - 3000:3000
    command:
      - npm
      - start
  mysql:
    image: mysql:8
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: api-db
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
volumes:
  mysql_data:
    driver: local